### PR TITLE
V7

### PR DESCRIPTION
**Pull request by urosgruber**
I've done a couple of changes from last version. Looks fine but I have couple of things to clear

- agent has some hardcoded check for `dist` folder and it's trying to find one from where the binary is. For that reason I put bin into `/usr/local/bin/datadog`  I'm not sure if this is a good practice for FreeBSD env
- I think port should be moved to **net** category
- should we split port to agent and integrations
- integrations list might need some filtering applied since not all are supported in FreeBSD

### CODE REVIEW

**Comment by fzipi** [comment]
Hey @urosgruber , you should also check python deps. Many integrations have dependencies on python packages, so the proper name should be installed with the integration. That's why we did the split.

**Comment by urosgruber** [comment]
> Hey @urosgruber , you should also check python deps. Many integrations have dependencies on python packages, so the proper name should be installed with the integration. That's why we did the split.

I'm not sure I understand about the **proper name**.

**Comment by fzipi** [comment]
Yeah, sorry. You can get the python `import` from all the python files, but you need to pass the `py37-<package-name>` instead.

**Review by danielhamelberg — COMMENTED** [review]
Hey, quick feedback, when the build completed, the install threw an exception related to the datadog user and group name. I changed those to dd-agent again and lived happily ever after.

**Comment by urosgruber** [comment]
I'm closing this in favour of #23

**Pull request closed without merging**
